### ISSUE TITLE
Upload attachment to the issued invoice

### ISSUE THREAD

**Issue by CZRubik** [malcanek/iDoklad-v2#12]
Would it be possible to add the possibility to upload an attachment to the issued invoice as described in the API documentation? If I'm not wrong this is with the current library not possible as I haven't seen appropriate header settings possible.

I was trying on my own to adapt but I'm failing and even with pure code with cURL I'm not able to get it working. Even I'm getting error 415 (which acc. doc should mean wrong headers), or directly answer error 500 from api server.

Thanks in advance.

**Comment by malcanek** [comment]
Hi,

thank you for your issue and sorry for my late response.

I digged into it a bit and finally got it working (you have to pull latest version). To send Attachment send request like this:
`$request = new \malcanek\iDoklad\request\iDokladRequest('Attachments/{documentId}/{documentType}');`
`$request->addFile(new CURLFile(path_to_your_file));`
`$response = $iDoklad->sendRequest($request);`

Please let me know if it works for you.
