### ISSUE TITLE
Získání přílohy dokladu či doklad jako PDF

### ISSUE THREAD

**Issue by tomas-kulhanek** [malcanek/iDoklad-v2#14]
Dobrý den, 
chtěl bych se optat, jak je možné stáhnout přílohu dokladu či doklad samotný? Protože když se dívám do `iDokladResponse`, tak tam se vždy parsuje json i když odpovědí je binární soubor.

**Comment by malcanek** [comment]
Dobrý den,

ano, toto byl nedostatek knihovny, děkuji za upozornění. Upravil jsem knihovnu tak, aby u `Attachments` endpointu neparsovala data, případně se dá nastavit na objektu `iDokladRequest`, že odpověď bude binary pomocí `$request->binary()`.
