### ISSUE TITLE
iDokladResponse

### ISSUE THREAD

**Issue by Mike-CZ** [malcanek/iDoklad-v2#2]
Porad mi to hazi chybu s iDokladResponse. V konstruktoru tridy se snazi pristupit k indexum, ktere nejsou inicializovany. Napriklad po vlozeni faktury v odpovedi nejsou prvky s indexy Data nebo Links, ale rovnou udeje o fakture (viz sekce Response Information: https://app.idoklad.cz/developer/Help/v2/cs/Api?apiId=POST-api-v2-IssuedInvoices)

**Comment by malcanek** [comment]
Děkuji za upozornění, chyba byla opravena, nyní objekt iDokladResponse reaguje podle dat, které se vrátí na výstupu.
