### ISSUE TITLE
iDoklad v2 - API - Account not supporting API calls

### ISSUE THREAD

**Issue by michalbursik** [malcanek/iDoklad-v2#5]
Hello,

When you are trying to connect your package with iDoklad "not supported API calls" ... means the account is not payed for, "invalid" response is returned (Your package returns JSON parsing error). With some debuging you will find out, but it's kind a hard to debug (I mean you have to debug the package itself.) I think there are is some curl header length problem.

**Comment by michalbursik** [comment]
Same thing happens when you are trying to get e.g. Contact with invalid ID. iDoklad is returning 404, but I will get just JSON parse error.

**Comment by malcanek** [comment]
Unfortunately I could not replicate error you are writing about. But I made a little fix so json_decode won´t try to decode empty response and variable data in response will be empty array. HTTP codes are working correctly for me, you can get them with method getCode() which is available in every response object.
