### ISSUE TITLE
Nefunkční DELETE

### ISSUE THREAD

**Issue by Evandar276** [malcanek/iDoklad-v2#6]
Ahoj,

nefunguje DELETE - minimálně pro PriceListItems/Batch/True - vrací HTTP chybu 415. Problém je v chybějící hlavičce Content-Type: application/json, která se přidává jenom pro 'POST', 'PUT', 'PATCH'. Po přidání 'DELETE' na tento seznam už funguje. Soubor iDoklad.php řádek 153.

```
$request = new \malcanek\iDoklad\request\iDokladRequest('PriceListItems/Batch/True', 'DELETE');
$request->addPostParameters(['Items' => [1, 2, 3, 4]);
$response = $iDoklad->sendRequest($request);
```

Díky za opravu.

PS: Netestoval jsem zatím další metody, ale možná s nimi bude stejný problém.

**Comment by malcanek** [comment]
Ahoj,

díky za upozornění. Chyba vznikla tím, že jsem vycházel z dokumentace (citace níže), která toto nezmiňuje. Jelikož jsem to testoval primárně na fakturách a zde se posílá poize id faktury jako parametr GET, tak se tato chyba neobjevila.

Nyní nasazen hotfix, který přidává DELETE do těchto metod, do budoucna udělám fix, aby se hlavička přidávala vždy když se přidávají POST parametry.

> Při použití requestů PUT, POST a PATCH je potřeba přidat do hlavičky záznam Content-Type 
Např.: Content-Type: application/json
